# vim:ft=kitty
## name: Glass Dark (True Panel Spec)

background              #0c0d0e
foreground              #fcfcfc
selection_background    #3daee9
selection_foreground    #ffffff

# Cursor
cursor                  #3daee9
cursor_text_color       #0c0d0e

# URLs & Links
url_color               #1d99f3

# Window borders
active_border_color     #3daee9
inactive_border_color   #1f2226
bell_border_color       #f67400

# Tab Bar
active_tab_background   #1f2326
active_tab_foreground   #fcfcfc
inactive_tab_background #0c0d0e
inactive_tab_foreground #a1a9b1
tab_bar_background      #0c0d0e

# Marks
mark1_foreground        #0c0d0e
mark1_background        #3daee9
mark2_foreground        #0c0d0e
mark2_background        #fdbc4b
mark3_foreground        #0c0d0e
mark3_background        #da4453

# --- ANSI Colors ---

#: Black
color0                  #0c0d0e
color8                  #404449

#: Red
color1                  #da4453
color9                  #ed1515

#: Green
color2                  #27ae60
color10                 #11d116

#: Yellow
color3                  #f67400
color11                 #fdbc4b

#: Blue
color4                  #1d99f3
color12                 #3daee9

#: Magenta
color5                  #9b59b6
color13                 #995dc6

#: Cyan
color6                  #00aaff
color14                 #3dc9e9

#: White
color7                  #c3c7d1
color15                 #ffffff
