# vim:ft=kitty
## name: Glass Dark (Panel Match - Live Blend)

background              #101314
foreground              #e8eaec
selection_background    #3daee9
selection_foreground    #101314

cursor                  #3daee9
cursor_text_color       #101314

url_color               #3daee9

active_border_color     #3daee9
inactive_border_color   #2a2e31
bell_border_color       #f67400

# Tab Bar
active_tab_background   #101314
active_tab_foreground   #ffffff
inactive_tab_background #202325
inactive_tab_foreground #82898f
tab_bar_background      #0e1011

# Marks
mark1_foreground        #0e1011
mark1_background        #3daee9
mark2_foreground        #0e1011
mark2_background        #fdbc4b
mark3_foreground        #0e1011
mark3_background        #da4453

# ANSI colors
color0  #101314
color8  #4a4f53
color1  #da4453
color9  #ed1515
color2  #27ae60
color10 #11d116
color3  #f67400
color11 #fdbc4b
color4  #1d99f3
color12 #3daee9
color5  #9b59b6
color13 #995dc6
color6  #00aaff
color14 #3dc9e9
color7  #a9afb4
color15 #ffffff
